
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jul 04 20:02:56 UYT 2017
//----------------------------------------------------

package com.ucu.teoria.dos.quaero.parser;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int NUM = 6;
  public static final int COLON = 4;
  public static final int STR = 8;
  public static final int TRUE = 9;
  public static final int EOF = 0;
  public static final int TAG = 7;
  public static final int FALSE = 10;
  public static final int error = 1;
  public static final int COMMA = 5;
  public static final int RPAREN = 3;
  public static final int LPAREN = 2;
}

