
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jul 17 18:54:53 UYT 2017
//----------------------------------------------------

package com.ucu.teoria.dos.quaero.parser;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int ROOT = 12;
  public static final int TAG = 7;
  public static final int DIFERENCIA = 19;
  public static final int RPAREN = 3;
  public static final int POINT = 15;
  public static final int CONCAT = 18;
  public static final int TRUE = 9;
  public static final int LPAREN = 2;
  public static final int INTERSEC = 16;
  public static final int COLON = 4;
  public static final int RE = 14;
  public static final int NUM = 6;
  public static final int COMMA = 5;
  public static final int EOF = 0;
  public static final int ELEMENTS = 13;
  public static final int COMILLA = 11;
  public static final int UNION = 17;
  public static final int FALSE = 10;
  public static final int error = 1;
  public static final int STR = 8;
}

